In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.ion()

# Exercise 00: Linear Gradient - Iterative Version

In [2]:
import numpy as np
from ex00.gradient import simple_gradient


x = np.array([[12.4956442],[ 21.5007972],[ 31.5527382],[ 48.9145838],[ 57.5088733]])
y = np.array([[37.4013816],[ 36.1473236],[ 45.7655287],[ 46.6793434],[ 59.5585554]])

# Example 0:
theta1 = np.array([[2],[ 0.7]])
res = simple_gradient(x, y, theta1)
# Output:
#array([[-19.0342574],[],[-586.66875564])
print(res)

# Example 1:
theta2 = np.array([[1],[ -0.4]])
res = simple_gradient(x, y, theta2)
# Output:
#array([[-57.86823748],[-2230.12297889]])
print(res)

[[ -19.0342574 ]
 [-586.66875564]]
[[  -57.86823748]
 [-2230.12297889]]


# Exercise 01: Linear Gradient - Vectorized Version

In [2]:
import numpy as np
from ex01.vec_gradient import gradient


x = np.array([[12.4956442],[ 21.5007972],[ 31.5527382],[ 48.9145838],[ 57.5088733]])
y = np.array([[37.4013816],[ 36.1473236],[ 45.7655287],[ 46.6793434],[ 59.5585554]])

# Example 0:
theta1 = np.array([[2],[ 0.7]])
res = gradient(x, y, theta1)
# Output:
#array([[-19.0342574],[],[-586.66875564])
print(res)

# Example 1:
theta2 = np.array([[1],[ -0.4]])
res = gradient(x, y, theta2)
# Output:
#array([[-57.86823748],[-2230.12297889]])
print(res)

[[ -19.0342574 ]
 [-586.66875564]]
[[  -57.86823748]
 [-2230.12297889]]


# Exercise 02: Gradient Descent

In [1]:
import numpy as np
from ex02.fit import fit_
from utils.prediction import predict_

x = np.array([[12.4956442], [21.5007972], [31.5527382], [48.9145838], [57.5088733]])
y = np.array([[37.4013816], [36.1473236], [45.7655287], [46.6793434], [59.5585554]])
theta = np.array([[1],[ 1]])

# Example 0:
theta1 = fit_(x, y, theta, alpha=5e-6, max_iter=15000)
print("## Example 0:\n theta1 = \n", theta1)
# Output:
#array([[1.40709365],
#[1.1150909 ]])


# Example 1:
pred = predict_(x, theta1)
print("\n## Example 1:\n predicion (predict_(x, theta1)) = \n", pred)
# Output:
#array([[15.3408728 ],
#[25.38243697],
#[36.59126492],
#[55.95130097],
#[65.53471499]])

## Example 0:
 theta1 = 
 [[1.40709384]
 [1.1150909 ]]

## Example 1:
 predicion (predict_(x, theta1)) = 
 [[15.34087293]
 [25.38243706]
 [36.59126497]
 [55.95130094]
 [65.53471493]]


# Exercise 03: Linear Regression with Class

In [1]:
import numpy as np
from ex03.my_linear_regression import MyLinearRegression as MyLR

x = np.array([[12.4956442], [21.5007972], [31.5527382], [48.9145838], [57.5088733]])
y = np.array([[37.4013816], [36.1473236], [45.7655287], [46.6793434], [59.5585554]])
lr1 = MyLR([2, 0.7])

# Example 0.0:
pred = lr1.predict_(x)
# Output:
#array([[10.74695094],
#[17.05055804],
#[24.08691674],
#[36.24020866],
#[42.25621131]])
print("### Example 0.0:\n", "lr1.predict_(x):\n", pred)

# Example 0.1:
loss_e = lr1.loss_elem_(lr1.predict_(x),y)
# Output:
#array([[710.45867381],
#[364.68645485],
#[469.96221651],
#[108.97553412],
#[299.37111101]])
print("\n### Example 0.1:\n", "lr1.loss_elem_(lr1.predict_(x),y):\n", loss_e)

# Example 0.2:
loss = lr1.loss_(lr1.predict_(x),y)
# Output:
#195.34539903032385
print("\n### Example 0.2:\n", "lr1.loss_(lr1.predict_(x),y):\n", loss)

# Example 1.0:
lr2 = MyLR([1, 1], 5e-8, 1500000)
lr2.fit_(x, y)
t2 = lr2.thetas
# Output:
#array([[1.40709365],
#[1.1150909 ]])
print("\n### Example 1.0:\n", "lr2.thetas:\n", t2)

# Example 1.1:
pred = lr2.predict_(x)
# Output:
#array([[15.3408728 ],
#[25.38243697],
#[36.59126492],
#[55.95130097],
#[65.53471499]])
print("\n### Example 1.1:\n", "lr2.predict_(x):\n", pred)

# Example 1.2:
MyLR.loss_elem_(lr2.predict_(x),y)
# Output:
#array([[486.66604863],
#[115.88278416],
#[ 84.16711596],
#[ 85.96919719],
#[ 35.71448348]])


# Example 1.3:
MyLR.loss_(lr2.predict_(x),y)
# Output:
#80.83996294128525

### Example 0.0:
 lr1.predict_(x):
 [[10.74695094]
 [17.05055804]
 [24.08691674]
 [36.24020866]
 [42.25621131]]

### Example 0.1:
 lr1.loss_elem_(lr1.predict_(x),y):
 [[710.45867381]
 [364.68645485]
 [469.96221651]
 [108.97553412]
 [299.37111101]]

### Example 0.2:
 lr1.loss_(lr1.predict_(x),y):
 195.34539903032385

### Example 1.0:
 lr2.thetas:
 [[1.40709365]
 [1.1150909 ]]

### Example 1.1:
 lr2.predict_(x):
 [[15.3408728 ]
 [25.38243697]
 [36.59126492]
 [55.95130097]
 [65.53471499]]


80.83996294128525

# Exercise 04: Practicing Linear Regression

In [ ]:
from sklearn.metrics import mean_squared_error
from pandas import read_csv
from ex03.my_linear_regression import MyLinearRegression as MyLR

data = pd.read_csv("ex04/are_blue_pills_magics.csv")
Xpill = np.array(data["Micrograms"]).reshape(-1,1)
Yscore = np.array(data["Score"]).reshape(-1,1)
# Example 1:
linear_model1 = MyLR(np.array([[89.0], [-8]]))
Y_model1 = linear_model1.predict_(Xpill)
print(linear_model1.mse_(Yscore, Y_model1))
print(mean_squared_error(Yscore, Y_model1))
# Output:
57.60304285714282
57.60304285714282
# Example 2:
linear_model2 = MyLR(np.array([[89.0], [-6]]))
Y_model2 = linear_model2.predict_(Xpill)
print(linear_model2.mse_(Yscore, Y_model2))
print(mean_squared_error(Yscore, Y_model2))
# Output:
232.16344285714285
232.16344285714285

# Exercise 05: Normalization I: Z-score Standardization

In [ ]:
# Example 1:
X = numpy.array([[0],[ 15],[ -9],[ 7],[ 12],[ 3],[ -21]])
zscore(X)
# Output:
array([-0.08620324, 1.2068453 , -0.86203236, 0.51721942, 0.94823559,
0.17240647, -1.89647119])
# Example 2:
Y = numpy.array([[2],[ 14],[ -13],[ 5],[ 12],[ 4],[ -19]])
zscore(Y)
# Output:
array([ 0.11267619, 1.16432067, -1.20187941, 0.37558731, 0.98904659,
0.28795027, -1.72770165])

# Exercise 06: Normalization II: Min-Max Standardization

In [ ]:
# Example 1:
X = np.array([[0],[ 15],[ -9],[ 7],[ 12],[ 3],[ -21]])
minmax(X)
# Output:
array([0.58333333, 1., 0.33333333, 0.77777778, 0.91666667,
0.66666667, 0.])
# Example 2:
Y = np.array([[2],[ 14],[ -13],[ 5],[ 12],[ 4],[ -19]])
minmax(Y)
# Output:
array([0.63636364, 1., 0.18181818, 0.72727273, 0.93939394,
0.6969697 , 0.]